Development
asegun-cod/experiencesdashboard pull request #4
Opened 2023-01-20 12:07 UTC by asegun-cod

This pull request addresses [issue #94](https://github.com/CDU-data-science-team/experiencesdashboard/issues/94) in the main project folder. 
it adds displays the whole data for the configured trust in the summary tab (only rows with the hidden flag set to 0 is returned) and gives users the functionality to do the following

1. _Edit any row in the data_: the edit is not written directly to the database. the actual database update happens when the user clicks the `save edit` button.
2. _Delete one or multiple rows_: the deletion doesn't actually delete the data from the database but sets the hidden flag to 1 

This also updates the comment tab so that users can search for comments using AND as against OR. This means only comments with the combined search words are returned.

2023-01-23 13:36 UTC, tomjemmett requested changes

2023-01-23 13:36 UTC, tomjemmett commented on R/mod_summary.R
> +        rowselected <<- dt_out$data[input$pat_table_rows_selected, "row_id"] %>%  unlist(use.name=F)
is `rowselected` previously defined? if not, it will be created in the global environment (with `<<-`), which could be a source of bugs. If `<<-` is required, consider definining at the start of this reactive, e.g. `rowselected <- NULL`

2023-01-23 13:36 UTC, tomjemmett commented on R/mod_summary.R
> +      DBI::dbGetQuery(db_conn, query)
may be worth wrapping this in a tryCatch block, incase the database statement fails. This would allow you to warn the user that the update failed

2023-01-23 14:37 UTC, asegun-cod commented on R/filter_text.R
>    searchTextInclude <- sub("[[:punct:]]$", "", trimws(search_string))
all of the above have now been resolved with [b6c60ac](https://github.com/asegun-cod/experiencesdashboard/commit/b6c60ac82d243d7c0e79c5dd2eae27d5285d1281)

2023-01-25 18:29 UTC, asegun-cod commented on R/mod_summary.R
> +        rowselected <<- dt_out$data[input$pat_table_rows_selected, "row_id"] %>%  unlist(use.name=F)
<<- wasn't required, so it has been changed to <-

2023-01-27 12:59 UTC, tomjemmett commented on R/filter_text.R
>    search_strings <- strsplit(filter_text, ",")[[1]] %>%
this no longer removes punctuation from the input strings - is this what you want?

2023-01-27 14:21 UTC, merged